# Generated by Django 3.0.3 on 2020-03-11 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('htmlcolorvalue', models.CharField(blank=True, max_length=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_order', models.PositiveIntegerField(default=1)),
                ('roomcode', models.CharField(max_length=50)),
                ('team_one_score', models.PositiveIntegerField(default=0)),
                ('team_two_score', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('gamemode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMode')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='si.Map')),
            ],
            options={
                'ordering': ['match_order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('is_captain', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=8)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateTimeField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('coproducer_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coproducer_one', to=settings.AUTH_USER_MODEL)),
                ('coproducer_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coproducer_two', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Game')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_order', models.PositiveIntegerField(default=1)),
                ('team_one_score', models.PositiveIntegerField(default=0)),
                ('team_two_score', models.PositiveIntegerField(default=0)),
                ('best_of', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_team_one', to='si.Team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_team_two', to='si.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('controls', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='si.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('assist', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('grabs', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('gamesplayed', models.PositiveIntegerField(default=0)),
                ('gamemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Map')),
                ('gamemode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.GameMode')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='si.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Series'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1', to='si.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_one_faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1side', to='si.GameFaction'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2', to='si.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two_faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2side', to='si.GameFaction'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Team'),
        ),
    ]
