# Generated by Django 3.0.3 on 2020-03-26 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('htmlcolorvalue', models.CharField(blank=True, max_length=12, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_order', models.PositiveIntegerField(default=1)),
                ('roomcode', models.CharField(blank=True, max_length=50, null=True)),
                ('team_one_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('team_two_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('gamemap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMap')),
                ('gamemode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMode')),
            ],
            options={
                'ordering': ['match_order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('is_captain', models.BooleanField(blank=True, default=False, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('wins', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('losses', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desc1', models.CharField(blank=True, max_length=500, null=True)),
                ('desc2', models.CharField(blank=True, max_length=500, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateTimeField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('coproducer_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_coproducer_one', to=settings.AUTH_USER_MODEL)),
                ('coproducer_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_coproducer_two', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='si.Game')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_producer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_order', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('team_one_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('team_two_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('best_of', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_team_one', to='si.Team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_team_two', to='si.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Team')),
            ],
            options={
                'ordering': ['series_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('deaths', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('assist', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goals', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grabs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('drops', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('wins', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('losses', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gamesplayed', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gamemap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si.GameMap')),
                ('gamemode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si.GameMode')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_team', to='si.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si.Series'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_one', to='si.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_one_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_one_faction', to='si.GameFaction'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_two', to='si.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_two_faction', to='si.GameFaction'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Team'),
        ),
    ]
