# Generated by Django 3.0.3 on 2020-03-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='desc3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
