# Generated by Django 3.0.3 on 2020-04-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='title',
            new_name='img_default_url',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='desc3',
        ),
        migrations.AddField(
            model_name='scene',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='video_default_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='desc1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='desc2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='scenes/img/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='scenes/vid/'),
        ),
    ]
