# Generated by Django 3.0.3 on 2020-03-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='GameMap',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='map',
            new_name='gamemap',
        ),
        migrations.AddField(
            model_name='gamefaction',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='si.Game'),
            preserve_default=False,
        ),
    ]
