# Generated by Django 3.0.3 on 2020-05-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0002_scene_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gamefaction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gamemap',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gamemode',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ['match']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['short_name']},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='losses',
            new_name='series_loss',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='wins',
            new_name='series_win',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='gamesplayed',
            new_name='loss',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='losses',
            new_name='win',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='wins',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si.Game'),
        ),
    ]
