# Generated by Django 3.0.3 on 2020-04-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0002_auto_20200406_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
