# Generated by Django 3.0.3 on 2020-03-13 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si', '0002_auto_20200312_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='gamefaction',
            name='htmlcolorvalue',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='gamemode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMode'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='roomcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_one', to='si.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_one_faction', to='si.GameFaction'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_two', to='si.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_two_faction', to='si.GameFaction'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_team', to='si.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='assist',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='deaths',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='drops',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='gamemap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si.GameMap'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='gamemode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si.GameMode'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='gamesplayed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='goals',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='grabs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='kills',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='losses',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='wins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='team_one_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='team_two_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='coproducer_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_coproducer_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='coproducer_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_coproducer_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='si.Game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_producer', to=settings.AUTH_USER_MODEL),
        ),
    ]
