# Generated by Django 3.0.3 on 2020-04-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0003_auto_20200406_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='scene/image/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='scene/video/'),
        ),
    ]
