# Generated by Django 3.0.3 on 2020-03-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0003_auto_20200313_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
