# Generated by Django 3.0.3 on 2020-05-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0003_auto_20200508_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player/image/'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Team'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Game'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='gamemap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMap'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='gamemode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMode'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='si.Match'),
        ),
    ]
