# Generated by Django 3.0.3 on 2020-03-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0004_auto_20200313_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gamemap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.GameMap'),
        ),
    ]
