# Generated by Django 3.0.3 on 2020-05-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0004_auto_20200509_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
