# Generated by Django 3.0.3 on 2020-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0004_auto_20200406_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='game/image/'),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gamemap/image/'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='gamemode/image/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team/image/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tournament/image/'),
        ),
    ]
