# Generated by Django 3.0.3 on 2020-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0005_playerstats_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_captain',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='is_captain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
