# Generated by Django 3.0.3 on 2020-03-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0005_auto_20200313_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['series_order']},
        ),
    ]
