# Generated by Django 3.0.3 on 2020-03-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0006_auto_20200313_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_one', to='si.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_team_two', to='si.Team'),
        ),
    ]
