# Generated by Django 3.0.3 on 2020-05-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0006_auto_20200512_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
