# Generated by Django 3.0.3 on 2020-05-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0007_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
