# Generated by Django 3.0.3 on 2020-05-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0008_auto_20200512_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ['match', 'team']},
        ),
        migrations.AddField(
            model_name='playerstats',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Series'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='si.Tournament'),
        ),
    ]
