export const GET_TOURNAMENTS = "GET_TOURNAMENTS";
export const GET_MATCHES_DETAILS = "GET_MATCHES_DETAILS";
export const GET_MATCHES = "GET_MATCHES";
export const GET_MATCH = "GET_MATCH";
export const UPDATE_MATCH = "UPDATE_MATCH";
export const UPDATE_MATCHES = "UPDATE_MATCHES";

export const UPDATE_JOKE = "UPDATE_JOKE";
export const UPDATE_POLLING_STATS = "UPDATE_POLLING_STATS";
export const POLL_START = "POLL_START";
export const POLL_STOP = "POLL_STOP";

export const GET_TEAMS = "GET_TEAMS";
export const GET_GAMES = "GET_GAMES";
export const GET_GAME_MAPS = "GET_GAME_MAPS";
export const GET_GAME_MODES = "GET_GAME_MODES";
export const GET_GAME_FACTIONS = "GET_GAME_FACTIONS";
export const GET_SCENES = "GET_SCENES";
export const GET_SCENE = "GET_SCENE";
export const UPDATE_SCENE_ACTIVATE = "UPDATE_SCENE_ACTIVATE";
export const UPDATE_SCENE_DEACTIVATE = "UPDATE_SCENE_DEACTIVATE";

export const GET_LEADS = "GET_LEADS";
export const DELETE_LEAD = "DELETE_LEAD";
export const ADD_LEAD = "ADD_LEAD";
export const CLEAR_LEADS = 'CLEAR_LEADS';

export const GET_SERIES = "GET_SERIES";
export const GET_SERIES_DETAILS = "GET_SERIES_DETAILS";
export const UPDATE_SERIES_END = "UPDATE_SERIES_END";
export const DELETE_SERIES = "DELETE_SERIES";
export const ADD_SERIES = "ADD_SERIES";
export const CLEAR_SERIES = 'CLEAR_LEADS';

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
